services:
  postgres:
    image: postgres:16
    container_name: midterm-postgres
    restart: always

    environment:
      POSTGRES_DB: midterm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gg25121326

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: