version: "3.9"

services:
  db:
    image: postgres:16
    container_name: finalproject-db
    environment:
      POSTGRES_DB: midterm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gg25121326
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:


